[package]
name = "adsbdb"
version = "0.0.1"
edition = "2021"
authors = ["Jack Wills <email@mrjackwills.com>"]
description = "aircraft & flightroute api"
repository = "https://github.com/mrjackwills/adsbdb"
license = "MIT"
readme = "README.md"

# [[bin]]
# name = "adsbdb"
# path = "src/main.rs"


[dependencies]
# axum = { git="https://github.com/tokio-rs/axum.git", branch = "handle-get-in-content-length-rejection" }
anyhow = "1.0"
async-trait = "0.1.53"
axum ="0.5.4"
dotenv = "0.15.0"
openssl = { version = '0.10', features = ["vendored"] }
parking_lot = "0.12.0"
redis = { version = "0.21.5", features = ["tokio-comp"] }
reqwest = {version = "0.11.9", features=["json", "native-tls"]}
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
sqlx = {version="0.5.13", features = ["runtime-tokio-rustls", "postgres", "time"]}
thiserror = "1.0.31"
tokio = {version = "1.17.0", features=["full"]}
tower = { version = "0.4", features = ["full"] }
tower-http = {version="0.3.2", features = ["full"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.9"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip=true
debug = false


